[build]
  publish = "."
  command = "pip install -r requirements.txt -t netlify/functions/extract"
 
[functions]
  directory = "netlify/functions"
 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
 
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
